icons_format = "{icon}"
[theme]
theme = "solarized-dark"
[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
format="$title.str(max_w:50)"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon / $available.eng(w:2) "

[[block]]
block = "net"
device = "wl40s20f3"
[[block.click]]
button = "left"
cmd = "/etc/profiles/per-user/doppler/bin/alacritty -e nmtui"

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{mem_total_used_percents}"
# format_swap = "{swap_used_percents}"
# 
# [[block]]
# block = "cpu"
# interval = 1
# 
# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"
# 
# [[block]]
# block = "battery"
# 
[[block]]
block = "sound"
# 
# [[block]]
# block = "backlight"
# 
# [[block]]
# block = "time"
# interval = 60
# format = "%a %d/%m %R"
