{ pkgs,inputs,... }:
{
  environment.systemPackages = with pkgs; [
    authenticator
    blender
    brave
    btop
    bun
    inputs.dgop.packages.${pkgs.stdenv.hostPlatform.system}.default
    freecad
    gimp3
    googleearth-pro
    imv
    inkscape
    librsvg
    mpv
    nautilus
    nextcloud-client
    nixd
    nixfmt
    nodejs
    openscad-unstable
    openscad-lsp
    ripgrep
    unzip
    virt-manager
    virt-viewer
    wf-recorder
    wl-clipboard
    yarn    
  ];
}
